services:
  redis:
    image: redis
    command: redis-server
    container_name: redis
    ports:
      - "6379:6379"
  
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_POOL_SIZE=5
      - ADDRESS=3000
    ports:
      - "8080:3000"